name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.12]
    env:
      DATABASE_URL: ${{ vars.DATABASE_URL }}
      SECRET_KEY: ${{ vars.SECRET_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Set up Postgresql
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '14'
          postgresql db: postgres
          postgresql user: postgres
          postgresql password: postgres

      - name: Start Postgresql
        run: sudo systemctl start postgresql
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter and unittest
        run: |
          make lint
          make test