name: task_manager

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.12]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - uses: actions/checkout@v2  
      - name: Django CI
        uses: UKnowWhoIm/django-test-action@v0.6
        with:
            settings-dir-path: "task_manager"

      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter and unittest
        run: |
          make lint
          make test