name: task_manager

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.12]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter
        run: |
          make lint
          
      - name: Django Testing
        env:
          DEBUG: ${{ secrets.MY_DEBUG }}
          SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
          DATABASE_URL: ${{ secrets.MY_DATABASE_URL }}
        run: |
          make test
          
      - name: Test coverage
        uses: paambaati/codeclimate-action@v3.1.1
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.MY_CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage-xml
          debug: true